"""Redacao competencias (C1-C5) gap analysis per school.

The ENEM redacao is graded across five competencies, each scored 0-200:
    C1 — Domínio da norma culta
    C2 — Compreensão da proposta
    C3 — Organização de argumentos
    C4 — Mecanismos linguísticos de coesão
    C5 — Proposta de intervenção

Data source: data/competencias_redacao_por_escola_{year}.csv, generated by
scripts/extract_competencias_redacao.py from raw INEP microdata. The pipeline
in update_enem_year.py averages the five competencies into one number, so
this CSV is the only place where per-competency data is preserved.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import pandas as pd

COMP_COLUMNS = ("media_c1", "media_c2", "media_c3", "media_c4", "media_c5")
COMP_LABELS = ("C1", "C2", "C3", "C4", "C5")
COMP_DESCRIPTIONS = {
    "C1": "Domínio da norma culta",
    "C2": "Compreensão da proposta",
    "C3": "Organização de argumentos",
    "C4": "Mecanismos linguísticos (coesão)",
    "C5": "Proposta de intervenção",
}


def compute_national_means(df: pd.DataFrame) -> Dict[str, float]:
    """National weighted mean per competency, weighted by n_redacoes per school."""
    means: Dict[str, float] = {}
    for idx, col in enumerate(COMP_COLUMNS):
        valid = df.dropna(subset=[col])
        if len(valid) == 0:
            means[f"c{idx + 1}"] = 0.0
            continue
        weights = valid["n_redacoes"].astype(float)
        values = valid[col].astype(float)
        total_weight = float(weights.sum())
        means[f"c{idx + 1}"] = float((values * weights).sum() / total_weight) if total_weight else 0.0
    return means


def _classify_gap(gap: float) -> str:
    if gap < -20:
        return "vermelho"
    if gap <= 0:
        return "amarelo"
    return "verde"


def infer_redacao_gaps(
    codigo_inep: str,
    df: Optional[pd.DataFrame],
    national_means: Dict[str, float],
) -> Optional[Dict[str, Any]]:
    """Per-competency gap analysis for a single school.

    Returns None when the school is not present in the dataset or the
    dataset itself is missing.
    """
    if df is None or len(df) == 0:
        return None

    rows = df[df["codigo_inep"] == codigo_inep]
    if len(rows) == 0:
        return None

    row = rows.iloc[0]
    competencias = []
    worst_gap = None
    worst_label = None

    for idx, col in enumerate(COMP_COLUMNS):
        label = COMP_LABELS[idx]
        media_escola = row.get(col)
        media_nacional = national_means.get(f"c{idx + 1}", 0.0)
        if pd.isna(media_escola):
            competencias.append({
                "competencia": label,
                "descricao": COMP_DESCRIPTIONS[label],
                "media_escola": None,
                "media_nacional": round(media_nacional, 1),
                "gap": None,
                "status": "indisponivel",
            })
            continue

        media_escola = float(media_escola)
        gap = media_escola - media_nacional
        status = _classify_gap(gap)
        competencias.append({
            "competencia": label,
            "descricao": COMP_DESCRIPTIONS[label],
            "media_escola": round(media_escola, 1),
            "media_nacional": round(media_nacional, 1),
            "gap": round(gap, 1),
            "status": status,
        })
        if worst_gap is None or gap < worst_gap:
            worst_gap = gap
            worst_label = label

    return {
        "codigo_inep": codigo_inep,
        "n_redacoes": int(row.get("n_redacoes", 0) or 0),
        "competencias": competencias,
        "gargalo_principal": worst_label,
    }
